############################################################################
# Enabled
############################################################################
# This flag indicates whether the module is enabled or disabled.
############################################################################
# Type: Boolean
# Default: false
############################################################################
enabled: true

############################################################################
# Default Formats
############################################################################
# Define which formatting will be used by default in all monitors
############################################################################
# Sizes: B (Bytes), KB (Kilobytes), GB (Gigabytes), TB (Terabytes)
#  - You can define rounding with "XX:Y" where Y is the number of decimals.
#  - Example: "GB:2" will display 2 decimal places
#
# Time/Date:
# - See this link:
# - https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
#
# Important:
# - You can override default format for each monitor by placing formats
# - under their configuration. Example:
#   Memory:
#    enabled: true
#    interval: 10
#    cacheable: true
#    formats:
#      memoryFormat: GB:2
############################################################################
formats:
  diskFormat: GB
  memoryFormat: MB
  dateFormat: yyyy-MM-dd
  timeFormat: HH:mm:ss
  dateTimeFormat: yyyy-MM-dd HH:mm:ss

############################################################################
# Monitors
############################################################################
# Configure which monitors are enabled and which interval they should
# be pooled from the system. I don't recommend less than 5 seconds.
# Cacheable monitors don't send the value repeatedly unless it changes.
############################################################################
monitors:
  # Google Chrome
  chrome:
    processes:
      - chrome
      - chrome64
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # AnyDesk
  AnyDesk:
    processes:
      - AnyDesk
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Discord
  Discord:
    processes:
      - Discord
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # OBS Studio
  OBS-Studio:
    processes:
      - obs
      - obs64
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Origin
  Origin:
    processes:
      - Origin
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Steam
  Steam:
    processes:
      - steam
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Rambox
  Rambox:
    processes:
      - Rambox
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Skype
  Skype:
    processes:
      - Skype
      - SkypeApp
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # TeamViewer
  TeamViewer:
    processes:
      - TeamViewer
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # VLC Media Player
  VLC:
    processes:
      - vlc
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Plex
  Plex:
    processes:
      - Plex
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Plex Media Server
  Plex-Server:
    processes:
      - Plex Media Server
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Zoom
  Zoom:
    processes:
      - Zoom
    windows:
    handles:
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60

  # Zoom
  Zoom-InMeeting:
    processes:
      - Zoom
    windows:
    handles:
      - ZPContentViewWndClass
    configs:
      enabled: true
      discoverable: true
      cacheable: true
      grouped: true
      interval: 60
