############################################################################
# Enabled
############################################################################
# This flag indicates whether the module is enabled or disabled.
############################################################################
# Type: Boolean
# Default: false
############################################################################
enabled: true

############################################################################
# Default Formats
############################################################################
# Define which formatting will be used by default in all monitors
############################################################################
# Sizes: B (Bytes), KB (Kilobytes), GB (Gigabytes), TB (Terabytes)
#  - You can define rounding with "XX:Y" where Y is the number of decimals.
#  - Example: "GB:2" will display 2 decimal places
#
# Time/Date:
# - See this link:
# - https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
############################################################################
formats:
  memoryFormat: MB
  dateTimeFormat: yyyy-MM-dd HH:mm:ss
  uptimeInSeconds: false

############################################################################
# Monitors
############################################################################
# Configure which monitors are enabled and which interval they should
# be pooled from the system. I don't recommend less than 5 seconds.
# Cacheable monitors don't send the value repeatedly unless it changes.
############################################################################
monitors:
  # Google Chrome
  chrome:
    processes:
      - chrome
      - chrome64
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Google Chrome
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # AnyDesk
  AnyDesk:
    processes:
      - AnyDesk
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: AnyDesk
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Discord
  Discord:
    processes:
      - Discord
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Discord
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # OBS Studio
  OBS-Studio:
    processes:
      - obs
      - obs64
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: OBS Studio
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Origin
  Origin:
    processes:
      - Origin
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Origin
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Steam
  Steam:
    processes:
      - steam
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Steam
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Rambox
  Rambox:
    processes:
      - Rambox
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Rambox
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Skype
  Skype:
    processes:
      - Skype
      - SkypeApp
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Skype
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # TeamViewer
  TeamViewer:
    processes:
      - TeamViewer
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: TeamViewer
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # VLC Media Player
  VLC:
    processes:
      - vlc
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: VLC Media Player
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Plex
  Plex:
    processes:
      - Plex
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Plex
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Plex Media Server
  Plex-Server:
    processes:
      - Plex Media Server
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Plex Server
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Zoom
  Zoom:
    processes:
      - Zoom
    windows:
    classnames:
    configs:
      enabled: false
      discoverable: true
      displayName: Zoom
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10

  # Zoom
  Zoom-InMeeting:
    processes:
      - Zoom
    windows:
    classnames:
      - ZPContentViewWndClass
    configs:
      enabled: false
      discoverable: true
      displayName: Zoom - In Meeting
      cacheable: true
      grouped: true
      compareType: 0
      interval: 10
