########################################################################
# Enabled
########################################################################
# This flag indicates whether the module is enabled or disabled.
########################################################################
# Type: Boolean
# Default: false
########################################################################
enabled: true

########################################################################
# Monitors
########################################################################
# Configure which monitors are enabled and which interval they should
# be pooled from the system. I don't recommend less than 5 seconds.
# Comment the line to disable the specific monitor.
########################################################################
# CPU               : CPU Usage
# Memory            : Memory (Usage, Available, Used, Total)
# HardDrive         : Hard Drives (Total Size, Free Space, Format, etc)
# Power             : Power (Status, Battery Status, Remaning Time, etc)
# IdleTime          : Idle Time (Per User)
# Display-Info      : Screen Width and Height (Per Display)
# Display-Screenshot: Screenshot (Per Display) - Recommended > 60 secs.
########################################################################
monitors:
  CPU: 10
  Memory: 10
  HardDrive: 60
  Power: 10
  IdleTime: 10
  Display-Info: 60
  Display-Screenshot: 60
