########################################################################
# Enabled
########################################################################
# This flag indicates whether the module is enabled or disabled.
########################################################################
# Type: Boolean
# Default: false
########################################################################
enabled: true

########################################################################
# Monitors
########################################################################
# Configure which monitors are enabled and which interval they should
# be pooled from the system. I don't recommend less than 5 seconds.
# Cacheable monitors don't send the value repeatedly unless it changes.
########################################################################
# CPU               : CPU Usage
# Memory            : Memory (Usage, Available, Used, Total)
# HardDrive         : Hard Drives (Total Size, Free Space, Format, etc)
# Power             : Power (Status, Battery Status, Remaning Time, etc)
# IdleTime          : Idle Time (Per User)
# Display-Info      : Screen Width and Height (Per Display)
# Display-Screenshot: Screenshot (Per Display) - Recommended > 60 secs.
########################################################################
monitors:
  CPU:
    enabled: true
    interval: 10
    cacheable: true
  Memory:
    enabled: true
    interval: 10
    cacheable: true
  HardDrive:
    enabled: true
    interval: 10
    cacheable: true
  Power:
    enabled: true
    interval: 10
    cacheable: true
  IdleTime:
    enabled: true
    interval: 10
    cacheable: true
  Display-Info:
    enabled: true
    interval: 60
    cacheable: true
  Display-Screenshot:
    enabled: true
    interval: 60
    cacheable: false
